"""
Integration test for ArUco marker detection.

Tests against the generated calibration sheet PNG to verify that
the detector finds all 4 markers with the correct IDs.

Requires: the calibration sheet to have been generated first.
Run scripts/generate_calibration_sheet.py if static/calibration_sheet.png is missing.
"""

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent))

import pytest
import cv2
import numpy as np

SHEET_PNG = Path(__file__).parent.parent / "static" / "calibration_sheet.png"


def test_calibration_sheet_exists():
    """The calibration sheet PNG must exist (generated by Phase 1 script)."""
    assert SHEET_PNG.exists(), (
        f"Calibration sheet not found at {SHEET_PNG}. "
        "Run: python scripts/generate_calibration_sheet.py"
    )


@pytest.fixture
def sheet_image():
    img = cv2.imread(str(SHEET_PNG))
    assert img is not None, "Could not load calibration sheet PNG"
    return img


def test_detect_all_four_markers(sheet_image):
    """ArUco detector must find all 4 markers (IDs 0-3) in the generated sheet."""
    from api.aruco_detector import detect_markers
    result = detect_markers(sheet_image)
    assert result is not None, "detect_markers returned None — markers not found"
    assert sorted(result.keys()) == [0, 1, 2, 3], \
        f"Expected marker IDs [0,1,2,3], got {sorted(result.keys())}"


def test_marker_corners_shape(sheet_image):
    """Each detected marker should have 4 corner points."""
    from api.aruco_detector import detect_markers
    result = detect_markers(sheet_image)
    for marker_id, corners in result.items():
        assert corners.shape == (4, 2), \
            f"Marker {marker_id}: expected (4,2) corner shape, got {corners.shape}"


def test_marker_centers_within_sheet(sheet_image):
    """All marker centres should be within the sheet image bounds."""
    from api.aruco_detector import detect_markers, get_marker_centers
    corners = detect_markers(sheet_image)
    centers = get_marker_centers(corners)

    h, w = sheet_image.shape[:2]
    for marker_id, (cx, cy) in centers.items():
        assert 0 <= cx <= w, f"Marker {marker_id} centre X={cx} is outside image width {w}"
        assert 0 <= cy <= h, f"Marker {marker_id} centre Y={cy} is outside image height {h}"


def test_homography_produces_valid_output(sheet_image):
    """Perspective correction should produce an image of the expected size."""
    from api.aruco_detector import detect_markers
    from api.homography import correct_perspective, OUTPUT_W, OUTPUT_H

    corners = detect_markers(sheet_image)
    corrected = correct_perspective(sheet_image, corners)

    assert corrected.shape[1] == OUTPUT_W, \
        f"Expected width {OUTPUT_W}, got {corrected.shape[1]}"
    assert corrected.shape[0] == OUTPUT_H, \
        f"Expected height {OUTPUT_H}, got {corrected.shape[0]}"
    assert corrected.dtype == np.uint8


def test_scale_calibration_within_tolerance(sheet_image):
    """Scale error after homography must be less than 2%."""
    from api.aruco_detector import detect_markers
    from api.homography import correct_perspective
    from api.scale_calibrator import calibrate_scale

    corners  = detect_markers(sheet_image)
    corrected = correct_perspective(sheet_image, corners)
    scale    = calibrate_scale(corrected)

    assert scale["ok"], \
        f"Scale error {scale['scale_error_pct']}% exceeds 2% tolerance"
